// 430A Tool and Die Maker — Red Seal Question Bank (135 Questions)
// Official breakdown: A=20, B=45, C=13, D=57. All original content.

export const CATEGORIES_430A = [
  { id: "A", name: "Common Occupational Skills", target: 20, color: "#e74c3c" },
  { id: "B", name: "Operates Machine-Tools", target: 45, color: "#e67e22" },
  { id: "C", name: "Heat Treatment", target: 13, color: "#2ecc71" },
  { id: "D", name: "Design, Development & Production Tools", target: 57, color: "#3498db" },
];

export const QUESTIONS_430A = [
  // ═══ BLOCK A: Common Occupational Skills (20) ═══
  // A-1: Safety (5)
  {id:1,cat:"A",q:"What is the first action when a coworker is injured by a press?",opts:["Move them away from the press","Stop the press, call for help, and assess without moving the victim unless in immediate danger","Resume production","Fill out paperwork"],ans:1,exp:"Stop the hazard source, call for emergency help, and assess the victim. Don't move them unless they're in immediate danger (fire, further crush risk). Spinal injuries can be worsened by moving.",type:"procedure"},
  {id:2,cat:"A",q:"What PPE is required when operating a surface grinder?",opts:["No PPE needed","Safety glasses with side shields, and no loose clothing, gloves, or jewelry near the spinning wheel","Steel-toed boots only","Hearing protection only"],ans:1,exp:"Grinding wheels spin at high RPM. Safety glasses protect from flying sparks/particles. Never wear gloves (catch in wheel), loose clothing, or jewelry near rotating machinery.",type:"recall"},
  {id:3,cat:"A",q:"A grinding wheel must be ring-tested before mounting. What indicates a cracked wheel?",opts:["A clear ringing tone","A dull thud instead of a clear ring","No sound at all","A very high pitch"],ans:1,exp:"A sound wheel produces a clear metallic ring when tapped. A cracked wheel produces a dull, dead thud. Never mount a cracked wheel — it can explode at operating speed.",type:"procedure"},
  {id:4,cat:"A",q:"The maximum gap between a grinding wheel and the tool rest must not exceed:",opts:["6mm (1/4\")","3mm (1/8\")","12mm (1/2\")","25mm (1\")"],ans:1,exp:"The tool rest gap must be 3mm (1/8\") or less to prevent workpieces from getting caught between the wheel and rest, which can shatter the wheel or throw the part.",type:"recall"},
  {id:5,cat:"A",q:"Lock-out/tag-out on a die press requires isolating which energy sources?",opts:["Only electrical","Electrical, pneumatic, hydraulic, mechanical (stored energy in springs/counterbalances), and gravity","Only the main switch","Only hydraulic"],ans:1,exp:"Presses have multiple energy sources: electrical (motor), hydraulic (ram), pneumatic (cushions/clamps), mechanical (flywheels, springs, counterbalances), and gravity (ram weight). All must be isolated.",type:"procedure"},

  // A-2: Maintains Machine-Tools (3)
  {id:6,cat:"A",q:"What is the purpose of regularly checking machine tool way oil levels?",opts:["Aesthetic appearance","Prevent metal-to-metal contact on slideways, reducing wear and maintaining accuracy","Cool the cutting tool","Lubricate the workpiece"],ans:1,exp:"Way oil lubricates the sliding surfaces (ways) of machine tools. Without it, metal-to-metal contact causes rapid wear, stick-slip motion, and loss of precision.",type:"recall"},
  {id:7,cat:"A",q:"How often should a CNC machine's spindle taper be cleaned?",opts:["Once a year","Before each tool change — any debris affects tool seating and runout","Only when visibly dirty","Never"],ans:1,exp:"Chips or contamination in the spindle taper prevent the toolholder from seating properly, causing runout, poor surface finish, vibration, and potential tool breakage.",type:"procedure"},
  {id:8,cat:"A",q:"A backlash compensator on a milling machine corrects:",opts:["Spindle runout","The play (lost motion) in the leadscrew and nut","Table leveling","Coolant flow"],ans:1,exp:"Backlash is the clearance between the leadscrew and nut. When reversing direction, this play causes positioning error. Compensators (mechanical or electronic) take up this slack.",type:"recall"},

  // A-3: Organizes Work (5)
  {id:9,cat:"A",q:"GD&T symbol ⊕ represents:",opts:["Flatness","Position tolerance","Concentricity","Parallelism"],ans:1,exp:"The circled cross (⊕) is the GD&T symbol for True Position — the most commonly used GD&T callout. It defines how far the actual feature center can deviate from the theoretically exact position.",type:"recall"},
  {id:10,cat:"A",q:"On a blueprint, what does a feature control frame contain?",opts:["Only the dimension","The GD&T symbol, tolerance value, and datum references","Only the material type","The part weight"],ans:1,exp:"A feature control frame reads left to right: geometric characteristic symbol | tolerance value (with modifiers) | primary datum | secondary datum | tertiary datum.",type:"recall"},
  {id:11,cat:"A",q:"What does MMC (Maximum Material Condition) mean in GD&T?",opts:["Minimum material","The condition where a feature contains the most material (largest shaft, smallest hole)","Maximum clearance","Minimum tolerance"],ans:1,exp:"MMC: largest shaft OD, smallest hole ID — the most material is present. Used with position tolerances to allow bonus tolerance as the feature departs from MMC.",type:"recall"},
  {id:12,cat:"A",q:"A first-angle projection drawing has the front view positioned:",opts:["Bottom left","Above the top view","The same as third-angle","With the right side view to the left of the front view"],ans:3,exp:"First-angle projection (common in Europe): the right side view is to the LEFT of the front view. Third-angle (North America): right side view is to the RIGHT. Key exam question.",type:"recall"},
  {id:13,cat:"A",q:"What CAD/CAM file format is standard for transferring 3D models between systems?",opts:["PDF","STEP (STP) or IGES","JPEG","DOC"],ans:1,exp:"STEP (.stp) and IGES (.igs) are universal 3D file exchange formats. STEP is newer and preserves more data. Used to transfer models between different CAD/CAM systems.",type:"recall"},

  // A-4: Benchwork (5)
  {id:14,cat:"A",q:"When hand-lapping a flat surface, what grit progression should be used?",opts:["Fine to coarse","Coarse to fine (e.g., 400 → 600 → 800 → 1200 grit)","Only one grit","Random order"],ans:1,exp:"Always progress from coarse to fine. Each successively finer grit removes the scratches from the previous grit, producing a mirror-like finish for die components.",type:"procedure"},
  {id:15,cat:"A",q:"A surface plate is used as a reference for:",opts:["Cutting metal","Providing a precision flat datum surface for layout, inspection, and measurement","Welding","Heat treatment"],ans:1,exp:"Surface plates (granite or cast iron) provide a precision flat reference surface accurate to millionths of an inch. Used with height gauges, indicators, and angle plates for layout and inspection.",type:"recall"},
  {id:16,cat:"A",q:"What is stoning used for in die making?",opts:["Sharpening drill bits","Removing small burrs and high spots from machined surfaces to achieve proper fit","Cutting metal","Measuring flatness"],ans:1,exp:"Stoning with precision stones removes burrs, raised edges, and high spots on machined die components. This is critical for proper shut height and component mating.",type:"recall"},
  {id:17,cat:"A",q:"When using Prussian blue (layout dye) for spotting die components, contact is indicated by:",opts:["Blue areas","Areas where blue is transferred (removed from one surface, deposited on the mating surface)","Areas with no blue","Random marks"],ans:1,exp:"Blue on the mating surface shows contact points. Even blue distribution = good fit. Concentrated spots indicate high points that need stoning or scraping for proper contact.",type:"procedure"},
  {id:18,cat:"A",q:"What type of file is used for finishing hardened steel die components?",opts:["Bastard file","Mill file (smooth or dead-smooth, single-cut)","Rasp","Double-cut file"],ans:1,exp:"Hardened steel requires a smooth or dead-smooth single-cut file. Coarser files skip and chatter on hardened surfaces. Diamond files are also used for extremely hard materials.",type:"recall"},

  // A-5: Communication & Mentoring (2)
  {id:19,cat:"A",q:"A tool and die maker documenting a die repair should record:",opts:["Nothing","Problem found, repair performed, parts replaced, clearances adjusted, and test results","Only the date","Only the part number"],ans:1,exp:"Complete documentation enables future troubleshooting, tracks die life, identifies recurring issues, and provides a maintenance history for cost analysis and scheduling.",type:"recall"},
  {id:20,cat:"A",q:"When mentoring an apprentice on a CNC EDM, the most effective approach is:",opts:["Let them read the manual alone","Demonstrate the setup, explain the parameters, then supervise their attempt with guidance","Just give them the G-code","Tell them not to touch it"],ans:1,exp:"Show-tell-do: demonstrate the procedure, explain why each step matters (parameters, flushing, electrode selection), then supervise their practice. EDM mistakes are expensive.",type:"recall"},

  // ═══ BLOCK B: Operates Machine-Tools (45) ═══
  // B-6: Power Saws (4)
  {id:21,cat:"B",q:"When cutting tool steel on a horizontal bandsaw, what coolant should be used?",opts:["No coolant","Soluble oil coolant to reduce heat and extend blade life","Water only","Air blast only"],ans:1,exp:"Soluble oil coolant lubricates the cut, reduces heat (preventing work hardening), extends blade life, and flushes chips. Dry cutting overheats and ruins both blade and material.",type:"recall"},
  {id:22,cat:"B",q:"The blade speed for cutting tool steel on a bandsaw should be:",opts:["Maximum speed","Slow speed (60-100 FPM) to prevent overheating and work hardening","Medium-fast","Same as for aluminum"],ans:1,exp:"Tool steels are hard and tend to work-harden. Slow blade speed with moderate feed prevents overheating. Higher speeds are used for softer materials like aluminum and mild steel.",type:"procedure"},
  {id:23,cat:"B",q:"A bandsaw blade wandering from the cut line is likely caused by:",opts:["Blade too tight","Dull blade, incorrect blade tension, or guides set too far from workpiece","Coolant too cold","Table too high"],ans:1,exp:"Wandering: dull teeth (can't maintain cut), low tension (blade deflects), guides too far from work (unsupported blade). Set guides close to the workpiece, check tension, and replace dull blades.",type:"critical"},
  {id:24,cat:"B",q:"The tooth pitch (TPI) for cutting thin stock on a bandsaw should be:",opts:["Coarse (3-4 TPI)","Fine (14-24 TPI) — minimum 3 teeth in contact with material thickness","Medium (6-8 TPI)","It doesn't matter"],ans:1,exp:"Minimum 3 teeth must be in contact with the material at all times. Thin stock needs fine pitch. Fewer teeth = straddling (teeth straddle the material) causing tooth breakage.",type:"recall"},

  // B-7: Drill Presses (4)
  {id:25,cat:"B",q:"The formula for drill press RPM (imperial) is:",opts:["RPM = π × D × CS","RPM = (12 × CS) ÷ (π × D)","RPM = D ÷ CS","RPM = CS × D × 12"],ans:1,exp:"RPM = (12 × Cutting Speed) ÷ (π × Diameter). CS in SFM, D in inches. For a 1/2\" HSS drill in mild steel (CS=90): RPM = (12×90)÷(3.14×0.5) = 688 RPM.",type:"critical"},
  {id:26,cat:"B",q:"When drilling a precision hole to be reamed, the drill should be:",opts:["Exactly the reamer size","0.010-0.015\" undersize to leave material for the reamer","0.050\" undersize","Oversize"],ans:1,exp:"Leave 0.010-0.015\" (0.25-0.4mm) for the reamer to remove. Too little leaves no material for the reamer; too much overloads the reamer and produces a poor finish.",type:"procedure"},
  {id:27,cat:"B",q:"A centre drill is used to:",opts:["Drill the final hole","Create a starting point (centre hole) to prevent the drill from wandering","Countersink only","Ream holes"],ans:1,exp:"Centre drills create a precise starting point. The pilot tip locates accurately, then the 60° body creates a funnel that guides the twist drill to start on center.",type:"recall"},
  {id:28,cat:"B",q:"What is the tap drill size for a 1/2\"-13 UNC thread?",opts:["1/2\"","27/64\" (0.4219\")","7/16\" (0.4375\")","29/64\""],ans:1,exp:"Tap drill = Major diameter − Pitch = 0.500 − (1/13) = 0.500 − 0.0769 = 0.4231 ≈ 27/64\" (0.4219\"). This formula is provided on the Red Seal exam.",type:"critical"},

  // B-8: Conventional Lathes (9)
  {id:29,cat:"B",q:"When turning between centers, the tailstock center should be set to:",opts:["Maximum pressure","Just enough pressure to support the work without binding or deflecting it","No pressure","Random pressure"],ans:1,exp:"Excessive tailstock pressure deflects the workpiece (taper), heats the center, and can damage the lathe. Too little lets the part chatter. Adjust for smooth rotation with light drag.",type:"procedure"},
  {id:30,cat:"B",q:"To turn a taper using the compound rest, the compound is set to:",opts:["0°","Half the included angle of the taper","The full included angle","90°"],ans:1,exp:"The compound is set to HALF the included angle because it creates the taper on one side only. For a 10° included taper, set the compound to 5°.",type:"critical"},
  {id:31,cat:"B",q:"The formula for taper per foot (TPF) is:",opts:["TPF = (D-d) × 12 ÷ L","TPF = D × L","TPF = L ÷ D","TPF = D + d"],ans:0,exp:"TPF = (D − d) × 12 ÷ L, where D = large diameter, d = small diameter, L = taper length in inches. This is a key formula on the Red Seal exam.",type:"critical"},
  {id:32,cat:"B",q:"Chatter marks on a turned surface are caused by:",opts:["Sharp cutting tool","Tool overhang too long, workpiece deflection, loose gibs, or improper speed/feed","Correct spindle speed","New chuck jaws"],ans:1,exp:"Chatter = vibration. Reduce tool overhang, support the workpiece (steady rest/follower rest), tighten gibs, adjust speed/feed, or change tool geometry to eliminate vibration.",type:"critical"},
  {id:33,cat:"B",q:"When thread cutting on a lathe, the compound rest is typically set to:",opts:["0° (perpendicular)","29° (for 60° thread) to provide a shearing cut on one flank","60°","45°"],ans:1,exp:"Setting the compound at 29° feeds the tool into the thread at an angle, cutting primarily on one flank. This produces a better finish and reduces chatter compared to plunge cutting at 0°.",type:"procedure"},
  {id:34,cat:"B",q:"A collet chuck provides better accuracy than a 3-jaw chuck because:",opts:["It's bigger","The collet grips the entire circumference uniformly with minimal runout (typically 0.001\" or less)","It's cheaper","It holds larger parts"],ans:1,exp:"Collets grip the full circumference with typically <0.001\" runout. 3-jaw chucks: 0.003-0.005\" runout. Collets are critical for precision tool and die work but limited to one size per collet.",type:"recall"},
  {id:35,cat:"B",q:"What lathe operation produces the best surface finish?",opts:["Rough turning","Fine turning with a small nose radius, slow feed, and high speed","Parting off","Drilling"],ans:1,exp:"Best finish: large nose radius (spreads the cut), fine feed (less tool marks), appropriate speed (material-dependent). Surface finish (Ra) improves with decreased feed rate.",type:"recall"},
  {id:36,cat:"B",q:"A live center in the tailstock differs from a dead center in that:",opts:["It's not used on a lathe","It rotates with the workpiece on internal bearings, eliminating friction heat","It doesn't support the work","It's made of plastic"],ans:1,exp:"Live centers have internal bearings so they rotate with the work. Dead centers are stationary and require lubrication. Live centers are preferred for higher speeds and longer runs.",type:"recall"},
  {id:37,cat:"B",q:"When boring on a lathe, the boring bar should be as large and short as possible to:",opts:["Look impressive","Maximize rigidity and minimize deflection/chatter","Increase speed","Reduce cost"],ans:1,exp:"A rigid boring bar resists cutting forces without deflecting. Deflection causes chatter, taper, and poor finish. Rule: bar length should not exceed 4× diameter for acceptable rigidity.",type:"recall"},

  // B-9: Conventional Milling (9)
  {id:38,cat:"B",q:"The formula for milling feed rate (IPM) is:",opts:["IPM = RPM × FPT × N","IPM = RPM ÷ N","IPM = FPT × RPM","IPM = N × CS"],ans:0,exp:"Feed Rate (IPM) = RPM × FPT × N. RPM = spindle speed, FPT = feed per tooth (chip load), N = number of teeth on cutter. This formula is provided on the Red Seal exam.",type:"critical"},
  {id:39,cat:"B",q:"Climb milling (down milling) differs from conventional milling in that:",opts:["The cutter rotates against the feed","The cutter rotation and feed direction are the same — producing a better finish with less deflection","It's slower","It's only for soft materials"],ans:1,exp:"Climb milling: cutter pushes the work down into the table (stable). Better finish, less heat, longer tool life. BUT requires a machine with backlash elimination to prevent table from being pulled.",type:"recall"},
  {id:40,cat:"B",q:"When milling a keyway, what type of cutter is typically used?",opts:["Face mill","Woodruff keyseat cutter or end mill depending on keyway type","Slitting saw only","Fly cutter"],ans:1,exp:"Woodruff keyseat cutters for Woodruff keys (semicircular). End mills for square/rectangular keyways (slot milling). The keyway width and depth are specified on the blueprint.",type:"recall"},
  {id:41,cat:"B",q:"An indexing head divides 360° into equal parts. To mill a hexagon (6 flats), the calculation is:",opts:["60 turns","40 ÷ 6 = 6-2/3 turns of the crank","360 ÷ 6 = 60 turns","6 turns"],ans:1,exp:"Simple indexing: turns = 40 ÷ N (where 40 is the standard worm ratio, N = number of divisions). 40 ÷ 6 = 6.667 turns = 6 full turns + 2/3 of a turn on the index plate.",type:"critical"},
  {id:42,cat:"B",q:"When using an edge finder on a milling machine, the spindle offset is:",opts:["Zero","Half the edge finder diameter (typically 0.100\")","The full diameter","1 inch"],ans:1,exp:"When the edge finder kicks out (eccentric tip aligns), the spindle center is exactly half the edge finder diameter from the workpiece edge. Standard edge finders = 0.200\" diameter, so offset = 0.100\".",type:"procedure"},
  {id:43,cat:"B",q:"A fly cutter on a milling machine is used for:",opts:["Drilling","Producing a flat surface with a single-point tool, typically for wide shallow facing cuts","Threading","Boring"],ans:1,exp:"Fly cutters use one insert/tool bit to face large flat surfaces. Cheaper than large face mills but slower (single cutting point). Good for tool and die surface finishing.",type:"recall"},
  {id:44,cat:"B",q:"When milling hardened tool steel (58-62 HRC), what cutter material should be used?",opts:["HSS","Carbide or CBN (cubic boron nitride) inserts","Cobalt only","Carbon steel"],ans:1,exp:"Hardened steel above 55 HRC requires carbide (with appropriate coating) or CBN tools. HSS cannot cut hardened steel effectively. CBN excels at very hard materials but is brittle.",type:"recall"},
  {id:45,cat:"B",q:"Tramming a milling head ensures:",opts:["Table flatness","The spindle is perpendicular to the table for accurate milling","Cutter sharpness","Coolant flow"],ans:1,exp:"Tramming aligns the spindle axis perpendicular to the table surface. A non-trammed head produces an uneven surface, taper on vertical surfaces, and inaccurate holes.",type:"recall"},
  {id:46,cat:"B",q:"What is the purpose of a rotary table on a milling machine?",opts:["Speed control","Allows circular interpolation and angular positioning of workpieces for radius milling, bolt holes, and die contours","Vibration dampening","Coolant delivery"],ans:1,exp:"Rotary tables provide rotational positioning for milling arcs, radii, bolt hole patterns, and die cavities. They can be indexed to precise angles for complex die features.",type:"recall"},

  // B-10: Grinding (9)
  {id:47,cat:"B",q:"Surface grinding wheel selection: what grit is used for finishing hardened die steel?",opts:["Coarse (36 grit)","Fine (80-120 grit) with aluminum oxide or CBN wheel","Very coarse (16 grit)","Wire brush"],ans:1,exp:"Fine grit (80-120) produces smooth finishes on hardened steel. Aluminum oxide (general purpose) or CBN (premium) wheels for ferrous materials. Silicon carbide is for non-ferrous and carbide.",type:"recall"},
  {id:48,cat:"B",q:"A grinding wheel is dressed to:",opts:["Make it look new","Expose fresh abrasive grains, true the wheel, and restore cutting ability","Increase wheel size","Change wheel colour"],ans:1,exp:"Dressing removes dull grains, clears loaded material, and reshapes the wheel face to true. A sharp, true wheel cuts cooler with better finish. Dress with diamond or star dresser.",type:"recall"},
  {id:49,cat:"B",q:"Grinding burn on a hardened surface indicates:",opts:["Proper grinding","Excessive heat that has tempered (softened) the surface — a serious defect","Normal discoloration","Good finish"],ans:1,exp:"Burn marks mean surface temperature exceeded tempering temperature, softening the hardened steel. This creates a soft spot that wears prematurely. Re-harden and re-grind, or scrap the part.",type:"critical"},
  {id:50,cat:"B",q:"When cylindrical grinding a die punch to final size, the final passes should be:",opts:["Heavy cuts to finish fast","Light (0.0001-0.0005\") spark-out passes to achieve size and roundness","Medium cuts","No final passes needed"],ans:1,exp:"Spark-out: feed zero and take light passes until sparks stop. This removes the elastic deflection of the part/wheel system, producing accurate diameter, roundness, and surface finish.",type:"procedure"},
  {id:51,cat:"B",q:"What type of grinding wheel is used for sharpening carbide cutting tools?",opts:["Aluminum oxide","Silicon carbide (green) or diamond wheel","CBN","Rubber bonded"],ans:1,exp:"Silicon carbide (green) wheels grind carbide effectively. Diamond wheels provide the best finish and longest life for carbide but are more expensive. Aluminum oxide is for steel only.",type:"recall"},
  {id:52,cat:"B",q:"Magnetic chuck holding force is reduced by:",opts:["Clean parts","Thin workpieces, non-ferrous materials, or dirty chuck surface","Larger workpieces","Heavier parts"],ans:1,exp:"Thin parts have less magnetic flux path. Non-ferrous materials (aluminum, brass) aren't attracted to magnets. Dirty surfaces reduce contact. Use parallels under thin parts; use fixtures for non-ferrous.",type:"recall"},
  {id:53,cat:"B",q:"Internal grinding (ID grinding) uses a smaller wheel because:",opts:["It's cheaper","The wheel must fit inside the bore diameter of the workpiece","It grinds faster","It's more accurate"],ans:1,exp:"The grinding wheel must be smaller than the bore being ground — typically 2/3 to 3/4 of the bore diameter for proper clearance and contact arc. Small wheels wear faster and need frequent dressing.",type:"recall"},
  {id:54,cat:"B",q:"When grinding a flat die plate, how is parallelism ensured?",opts:["Eyeball it","Grind one side, flip the part, and grind the other side referencing the ground surface. Check with indicator.","Grind only one side","Use a file"],ans:1,exp:"Grind one face flat. Clean and place ground face down on the magnetic chuck. Grind the second face. Now both faces are parallel to each other. Verify with indicator across the part.",type:"procedure"},
  {id:55,cat:"B",q:"Wheel loading (clogging) is most likely when grinding:",opts:["Hardened steel","Soft materials like aluminum or soft steel that stick to the wheel","Cast iron","Carbide"],ans:1,exp:"Soft, ductile materials (aluminum, soft steel, copper) tend to weld into the wheel pores, loading it. Use open-structure wheels, coarser grit, and proper coolant to reduce loading.",type:"recall"},

  // B-11: CNC Machines (6)
  {id:56,cat:"B",q:"In CNC programming, G41 activates:",opts:["Canned drilling cycle","Cutter radius compensation left","Circular interpolation","Tool change"],ans:1,exp:"G41 = cutter compensation left (tool left of programmed path). G42 = right. CRC lets you program the part geometry directly while the control offsets for the tool radius.",type:"recall"},
  {id:57,cat:"B",q:"A CNC machine's work coordinate offset (G54) establishes:",opts:["Tool length","The relationship between machine zero and the workpiece zero (part origin)","Spindle speed","Feed rate"],ans:1,exp:"G54 (through G59) sets work coordinate systems — telling the machine where the part is on the table. Machine zero is fixed; work zero is set by the operator for each setup.",type:"recall"},
  {id:58,cat:"B",q:"What does G17 specify in a CNC milling program?",opts:["Tool change","XY plane selection (for circular interpolation and cutter compensation)","Z-axis rapid","Dwell time"],ans:1,exp:"G17 = XY plane, G18 = XZ plane, G19 = YZ plane. This tells the machine which plane to use for circular interpolation (G02/G03) and cutter compensation.",type:"recall"},
  {id:59,cat:"B",q:"CNC tool length offset (G43) compensates for:",opts:["Workpiece material","Differences in tool length so the programmed Z positions remain correct regardless of which tool is loaded","Tool diameter","Feed rate"],ans:1,exp:"Each tool has a different length. G43 H__ applies the tool length offset so Z-axis positions are measured from the workpiece surface, not the spindle nose. Critical for tool changes.",type:"recall"},
  {id:60,cat:"B",q:"In CNC wire EDM, what is the purpose of the guide dies?",opts:["Cut the wire","Support and position the wire electrode precisely above and below the workpiece","Hold the workpiece","Supply coolant"],ans:1,exp:"Upper and lower guide dies (diamond or sapphire) position the wire with micron accuracy. Worn guides cause poor accuracy and taper. They must be replaced at recommended intervals.",type:"recall"},
  {id:61,cat:"B",q:"A CNC program's G28 command returns the machine to:",opts:["Work zero","Machine home (reference point) via an intermediate point","The last tool position","G54 origin"],ans:1,exp:"G28 returns to machine home position through an intermediate point (to avoid collisions). Used before tool changes and at program end. G28 X0 Y0 Z0 returns via current position.",type:"recall"},

  // B-12: EDM Machines (4)
  {id:62,cat:"B",q:"In sinker EDM, the dielectric fluid serves what purposes?",opts:["Only cooling","Insulates the gap, flushes debris, cools the electrode and workpiece, and controls the spark","Only lubrication","Only visibility"],ans:1,exp:"EDM dielectric (usually hydrocarbon oil): insulates until breakdown voltage, controls spark characteristics, flushes erosion debris, and cools both electrode and workpiece.",type:"recall"},
  {id:63,cat:"B",q:"Electrode material selection for sinker EDM — graphite vs copper:",opts:["No difference","Graphite: faster removal, less wear, better for rough cuts. Copper: better finish, tighter tolerances, less overcut","Copper is always better","Graphite is always better"],ans:1,exp:"Graphite: machinable, lighter, faster metal removal, lower wear ratio on steel. Copper: superior surface finish, tighter corners, better for small detailed features and carbide work.",type:"recall"},
  {id:64,cat:"B",q:"EDM overcut (side gap) is typically in the range of:",opts:["0.1\"","0.001-0.010\" per side depending on power settings","0.050\" per side","0.500\""],ans:1,exp:"Overcut (spark gap) varies with power settings: roughing = larger gap (~0.005-0.010\"), finishing = smaller (~0.001-0.003\"). The electrode must be undersized by the overcut amount per side.",type:"critical"},
  {id:65,cat:"B",q:"Wire EDM can cut what types of materials?",opts:["Only soft metals","Any electrically conductive material including hardened tool steel, carbide, and titanium","Only aluminum","Only copper"],ans:1,exp:"Wire EDM cuts any conductive material regardless of hardness — hardened tool steel, carbide, titanium, copper, inconel. Hardness doesn't affect cutting speed. It cannot cut non-conductive materials.",type:"recall"},

  // ═══ BLOCK C: Heat Treatment (13) ═══
  // C-13: Heat Treats Materials (10)
  {id:66,cat:"C",q:"Hardening of tool steel involves heating to the critical temperature and then:",opts:["Slow cooling in the furnace","Rapid cooling (quenching) in oil, air, or water depending on the steel type","Holding at room temperature","Cooling in sand"],ans:1,exp:"Heating above critical temperature austenizes the steel. Rapid quenching traps carbon in a martensitic structure = hard. Quench medium depends on steel type: O-series=oil, A-series=air, W-series=water.",type:"recall"},
  {id:67,cat:"C",q:"After hardening, steel is tempered to:",opts:["Make it harder","Reduce brittleness while retaining most of the hardness","Soften it completely","Change its colour only"],ans:1,exp:"As-quenched martensite is very hard but brittle. Tempering (reheating to 300-600°F) relieves internal stresses, restoring some toughness at the expense of slight hardness reduction.",type:"recall"},
  {id:68,cat:"C",q:"D2 tool steel is classified as:",opts:["Water-hardening","Air-hardening high-chromium cold work tool steel","Oil-hardening","High-speed steel"],ans:1,exp:"D2 is high-carbon, high-chromium (12%) cold work die steel. Air-hardening with excellent wear resistance. Widely used for blanking dies, forming dies, and punches.",type:"recall"},
  {id:69,cat:"C",q:"What is the critical temperature (austenitizing) range for most tool steels?",opts:["200-400°F","1450-2050°F (790-1120°C) depending on the alloy","500-700°F","2500-3000°F"],ans:1,exp:"Critical temperature varies by alloy: O1 = ~1475°F, D2 = ~1850°F, A2 = ~1750°F, S7 = ~1725°F, H13 = ~1875°F. Always follow the steel manufacturer's specifications.",type:"recall"},
  {id:70,cat:"C",q:"Annealing steel involves:",opts:["Rapid quenching","Heating above critical temperature and SLOW cooling (furnace cool) to soften the material","Heating to room temperature","Quenching in water"],ans:1,exp:"Annealing: heat above critical temp, soak, then furnace-cool very slowly. This produces the softest possible condition for easier machining. Reverse of hardening.",type:"recall"},
  {id:71,cat:"C",q:"Stress relieving is performed at what temperature range?",opts:["Above critical temperature","Below critical temperature (typically 1000-1200°F / 540-650°C)","Room temperature","Freezing temperature"],ans:1,exp:"Stress relieving heats below the critical temperature to relax internal stresses from machining, welding, or forming WITHOUT changing the hardness or microstructure.",type:"recall"},
  {id:72,cat:"C",q:"Cryogenic treatment (deep freezing) of tool steel at -120°F or colder is done to:",opts:["Make the steel colder","Convert retained austenite to martensite for maximum hardness and wear resistance","Soften the steel","Clean the steel"],ans:1,exp:"After quenching, some austenite remains unconverted (retained austenite). Cryogenic treatment converts this to martensite, increasing hardness, dimensional stability, and wear resistance.",type:"recall"},
  {id:73,cat:"C",q:"Case hardening (carburizing) produces:",opts:["Through hardness","A hard outer case with a tough, ductile core","A soft surface","Uniform softness"],ans:1,exp:"Carburizing adds carbon to the surface layer at high temperature. After quenching, the carbon-enriched case is hard (wear-resistant) while the low-carbon core remains tough (shock-resistant).",type:"recall"},
  {id:74,cat:"C",q:"Decarburization during heat treatment is caused by:",opts:["Too much carbon","Carbon loss at the surface from exposure to oxygen/atmosphere at high temperature","Adding carbon","Low temperature"],ans:1,exp:"Decarb: surface carbon reacts with oxygen/CO₂ in the furnace atmosphere, depleting carbon at the surface. Results in a soft skin that won't harden properly. Prevented with controlled atmosphere or vacuum furnace.",type:"critical"},
  {id:75,cat:"C",q:"Salt bath heat treatment offers what advantage over atmosphere furnaces?",opts:["Lower cost always","Rapid uniform heating, protection from oxidation/decarb, and precise temperature control","Only for low temperatures","Only for aluminum"],ans:1,exp:"Salt baths: fast heat transfer (liquid contact), no atmosphere exposure (prevents decarb/oxidation), very uniform temperature. Used for hardening, tempering, and austempering of tool steel.",type:"recall"},

  // C-14: Tests Heat Treated Materials (3)
  {id:76,cat:"C",q:"Rockwell C hardness testing uses what indenter and load?",opts:["Steel ball, 100 kgf","Diamond cone (brale), 150 kgf major load","Steel ball, 60 kgf","Diamond pyramid, 50 kgf"],ans:1,exp:"Rockwell C: diamond cone indenter (brale), 10 kgf minor load + 150 kgf major load. Used for hardened steels (20-68 HRC). Rockwell B uses a ball indenter for softer materials.",type:"recall"},
  {id:77,cat:"C",q:"A hardened D2 die component should test approximately:",opts:["30-35 HRC","58-62 HRC","45-50 HRC","70-75 HRC"],ans:1,exp:"D2 tool steel properly hardened and tempered: 58-62 HRC is typical working range. Below 58 = under-hardened (poor wear). Above 62 = possibly under-tempered (too brittle).",type:"recall"},
  {id:78,cat:"C",q:"A file test is a quick shop method to estimate hardness. A file will:",opts:["Always cut the material","Skate over (not cut) material harder than the file (~62-65 HRC) and bite into softer material","Never indicate hardness","Only work on aluminum"],ans:1,exp:"A standard file is ~62-65 HRC. If the file slides without cutting, the material is at least that hard. If it bites in and cuts, the material is softer. Quick go/no-go field test.",type:"procedure"},

  // ═══ BLOCK D: Design, Development & Production Tools (57) ═══
  // D-15: Production Tool Design (9)
  {id:79,cat:"D",q:"Die clearance for blanking is typically what percentage of material thickness?",opts:["1-2%","5-10% per side (depending on material type and thickness)","25%","50%"],ans:1,exp:"Blanking clearance = 5-10% of material thickness per side for mild steel. Harder materials need more clearance. Too little clearance = excess tonnage and edge chipping. Too much = burrs and poor edge.",type:"critical"},
  {id:80,cat:"D",q:"In a blanking die, the punch is made to the:",opts:["Die size","Part size (blank size), and the die opening is enlarged by the clearance","Clearance size","Random size"],ans:1,exp:"For blanking: the PUNCH = part size. The DIE = part size + clearance per side. For punching (hole making): DIE = hole size, PUNCH = hole size − clearance per side.",type:"critical"},
  {id:81,cat:"D",q:"What is the formula for blanking force (tonnage)?",opts:["Force = Area × Speed","Force = Perimeter × Thickness × Shear Strength","Force = Weight × Gravity","Force = Pressure × Volume"],ans:1,exp:"Cutting Force = L × T × S. L = cut perimeter length, T = material thickness, S = shear strength of material. This formula is provided on the Red Seal exam.",type:"critical"},
  {id:82,cat:"D",q:"Shear on a blanking punch reduces required tonnage by:",opts:["Increasing the cut area","Distributing the cut over the stroke so not all cutting occurs simultaneously","Reducing material thickness","Eliminating clearance"],ans:1,exp:"Shear (angle ground on the punch face) staggers the cutting action across the stroke length, reducing peak force by approximately the ratio of shear to material thickness.",type:"recall"},
  {id:83,cat:"D",q:"A progressive die performs:",opts:["One operation","Multiple operations in sequence as the strip advances through stations with each press stroke","Only blanking","Only forming"],ans:1,exp:"Progressive dies perform multiple operations (pierce, form, bend, blank) at successive stations. The strip advances one pitch per stroke. Very high production rates.",type:"recall"},
  {id:84,cat:"D",q:"When designing a draw die, the blank holding force must be:",opts:["Maximum","Enough to prevent wrinkling but not so much that it restricts material flow and causes tearing","Zero","Equal to punch force"],ans:1,exp:"Too much blank holder force = material can't flow into the die cavity = tearing/fracturing. Too little = material wrinkles/buckles. Finding the balance is critical in draw die design.",type:"critical"},
  {id:85,cat:"D",q:"The bend allowance formula accounts for:",opts:["Only the inside radius","Material stretching at the neutral axis during bending: BA = (r + C) × (2π × angle/360)","Only the material thickness","Only the bend angle"],ans:1,exp:"Bend allowance (BA) = (radius + C variable) × (2π × angle ÷ 360). C variable depends on the ratio of radius to thickness. This formula is provided on the Red Seal exam.",type:"critical"},
  {id:86,cat:"D",q:"Spring-back in bending operations is compensated by:",opts:["Ignoring it","Over-bending past the desired angle, or using a bottoming die","Under-bending","Using a softer material"],ans:1,exp:"Material elastically recovers (springs back) after the punch withdraws. Compensate by: over-bending (empirically determined), bottoming (coining the bend), or using a spring-back compensation radius.",type:"recall"},
  {id:87,cat:"D",q:"Minimum bend radius to avoid cracking is typically:",opts:["Zero (sharp bend)","1× to 3× material thickness depending on material type and grain direction","10× thickness","20× thickness"],ans:1,exp:"Minimum bend radius depends on: material type (soft aluminum ~0.5T, stainless ~2T), grain direction (bend across grain), temper, and thickness. Bending with the grain cracks easier.",type:"recall"},

  // D-16: Develops Prototype (6)
  {id:88,cat:"D",q:"A prototype punch made from A2 tool steel is used to:",opts:["Mass produce parts","Prove the design concept, check dimensions, and test function before committing to production tooling","Decorate the shop","Fill orders"],ans:1,exp:"Prototyping validates: part dimensions, material flow, strip layout, timing, die function, and identifies design issues before investing in expensive production-quality tooling.",type:"recall"},
  {id:89,cat:"D",q:"When prototyping a formed part, what method can quickly produce a test piece?",opts:["Wait for the production die","CNC machining from solid, 3D printing, or hand forming using soft tooling","Only casting","Only welding"],ans:1,exp:"Quick prototype methods: CNC from solid stock, 3D printing (for form/fit), soft tooling (kirksite/epoxy dies for short runs), or hand forming. Validates design before hard tooling.",type:"recall"},
  {id:90,cat:"D",q:"Wire EDM is commonly used in die prototyping because:",opts:["It's the fastest method","It cuts hardened steel to tight tolerances without cutting forces that could distort thin sections","It's the cheapest","It only works on soft materials"],ans:1,exp:"Wire EDM cuts complex profiles in hardened tool steel with no mechanical cutting forces. No distortion of thin sections, sharp internal corners possible, and excellent accuracy (±0.0001\").",type:"recall"},
  {id:91,cat:"D",q:"A die tryout involves:",opts:["Building the die","Running test parts in the press to verify die function, part quality, and identify issues","Designing the die","Quoting the job"],ans:1,exp:"Die tryout: install die in press, run parts at various speeds/pressures, check dimensions, surface quality, strip progression, and identify any problems (burrs, mis-hits, die interference).",type:"recall"},
  {id:92,cat:"D",q:"Checking a prototype stamped part with a CMM (Coordinate Measuring Machine) provides:",opts:["Only visual assessment","Precise 3D dimensional verification compared to CAD model or blueprint specifications","Only weight measurement","Only hardness data"],ans:1,exp:"CMMs probe multiple points on the part surface, comparing actual geometry to nominal CAD data. They report deviations, profiles, GD&T values, and generate inspection reports.",type:"recall"},
  {id:93,cat:"D",q:"During die tryout, if the part shows excessive burr on the blanked edge, the likely cause is:",opts:["Press too fast","Insufficient cutting clearance, dull cutting edges, or misalignment between punch and die","Material too thin","Coolant issue"],ans:1,exp:"Burr formation: dull edges (re-sharpen), too much clearance (rework die), punch/die misalignment (re-align), or material harder than expected. Inspect cutting edges first.",type:"critical"},

  // D-17: Fits and Assembles Production Tools (15)
  {id:94,cat:"D",q:"Press-fit interference between a punch and its retainer is typically:",opts:["0.050\"","0.0005-0.001\" per side","Clearance fit","0.010\""],ans:1,exp:"Typical press-fit interference: 0.0005-0.001\" per side ensures the punch is securely held without distortion. Too much interference can crack hardened components.",type:"recall"},
  {id:95,cat:"D",q:"Die set guide pins and bushings provide:",opts:["Only alignment during assembly","Precise alignment between upper and lower die shoes during press operation","Only decoration","Only support"],ans:1,exp:"Guide pins (mounted in one shoe) slide through precision bushings (in the other shoe) to maintain alignment under the dynamic forces of stamping. Critical for punch-to-die alignment.",type:"recall"},
  {id:96,cat:"D",q:"When assembling a compound die, the critical dimension to verify is:",opts:["Die colour","Shut height and uniform clearance between all punches and die openings","The number of bolts","The paint finish"],ans:1,exp:"Shut height determines press compatibility. Uniform clearance ensures consistent edge quality around the entire profile. Check with feeler gauges or by examining test pieces.",type:"procedure"},
  {id:97,cat:"D",q:"Dowel pins in a die assembly serve what purpose?",opts:["Hold the die together","Precisely locate components relative to each other — maintaining alignment if disassembled and reassembled","Only decoration","Act as springs"],ans:1,exp:"Dowel pins establish precise relative positions. When a die is disassembled for sharpening, dowels ensure all components return to their exact original positions upon reassembly.",type:"recall"},
  {id:98,cat:"D",q:"Shut height of a die is measured from:",opts:["Table to ram","Bottom of the lower shoe to top of the upper shoe when die is fully closed","Punch tip to die face","Guide pin length"],ans:1,exp:"Shut height = total die height in the closed position. Must match the press's shut height range (with adjustment). Too tall = die won't close. Too short = press bottoms out.",type:"recall"},
  {id:99,cat:"D",q:"Spring strippers in a die perform what function?",opts:["Only holding the strip","Hold the strip flat, strip the material off the punches on the upstroke, and guide the punches","Only aesthetics","Only as a safety guard"],ans:1,exp:"Spring strippers: hold material flat during cutting (prevents distortion), strip material off punches as they withdraw, and guide punches for better alignment. Pressure must be set correctly.",type:"recall"},
  {id:100,cat:"D",q:"When fitting a die section with a clearance of 0.002\" per side, what measuring tool verifies this?",opts:["Ruler","Feeler gauge or shim stock between punch and die","Tape measure","Protractor"],ans:1,exp:"Feeler gauges are thin steel strips of known thickness. Insert between the punch and die at multiple points to verify uniform clearance. Optical comparators can also verify clearance.",type:"procedure"},
  {id:101,cat:"D",q:"A ball-lock punch retainer allows:",opts:["Permanent installation only","Quick removal and replacement of punches without disassembling the die","Only round punches","Only square punches"],ans:1,exp:"Ball-lock systems use spring-loaded balls that lock into a groove in the punch. Press a release button to change punches in seconds. Critical for dies that need frequent sharpening.",type:"recall"},
  {id:102,cat:"D",q:"Heel blocks in a die absorb:",opts:["Vibration only","Lateral forces that would otherwise push the upper and lower die halves out of alignment","Sound","Heat"],ans:1,exp:"Heel blocks (guide blocks) resist the side thrust from forming, bending, and cam operations. Without them, lateral forces misalign the die, damaging punches and die sections.",type:"recall"},
  {id:103,cat:"D",q:"When grinding a die section to achieve a specific clearance angle, the surface grinder table is:",opts:["Level","Tilted to the required angle using a sine bar or angle fixture","Raised higher","Lowered"],ans:1,exp:"Die clearance angles (typically 1/4° to 2° per side) are ground using a sine bar set to the exact angle. The workpiece sits on the sine bar and is ground on the tilted surface.",type:"procedure"},
  {id:104,cat:"D",q:"A die component marked 'EDM' on the blueprint must be:",opts:["Engraved by hand","Machined by electrical discharge machining for features that can't be conventionally machined","Extremely dull material","Extra deep milled"],ans:1,exp:"EDM callouts indicate features like sharp internal corners, complex cavities, or very tight tolerances in hardened steel that can't be achieved by conventional milling or grinding.",type:"recall"},
  {id:105,cat:"D",q:"Pilots in a progressive die are used to:",opts:["Steer the press","Precisely locate the strip at each station by entering previously pierced holes","Drive the motor","Guide the operator"],ans:1,exp:"Pilots (spring-loaded pins) enter pilot holes punched at a previous station, pulling the strip into exact position before the press closes. This ensures station-to-station registration accuracy.",type:"recall"},
  {id:106,cat:"D",q:"Die springs are colour-coded by:",opts:["Brand","Deflection rate (spring force) — green=light, blue=medium, red=heavy, yellow=extra heavy","Material only","Length only"],ans:1,exp:"ISO colour coding: Green=light, Blue=medium, Red=heavy, Yellow=extra heavy duty. Selecting the correct spring rate is critical for stripper pressure, pad pressure, and die function.",type:"recall"},
  {id:107,cat:"D",q:"Backing plates in a die are made from hardened steel to:",opts:["Look professional","Distribute punch force over the die shoe and prevent punches from driving into the softer shoe material","Only add weight","Only for colour"],ans:1,exp:"Without backing plates, hardened punches under tonnage would embed into the softer die shoe. Backing plates (heat-treated to 58-62 HRC) distribute the force over a larger area.",type:"recall"},
  {id:108,cat:"D",q:"Timing of operations in a progressive die is controlled by:",opts:["The operator's speed","The relative height of punches, cams, and forming stations — taller features engage material first","Only the press speed","Only the strip feed"],ans:1,exp:"Timing ensures operations occur in the correct sequence during the single press stroke. Taller components hit first. Cams and aerial cams control lateral movements. Critical for complex progressive dies.",type:"recall"},

  // D-18: Proves Out Production Tools (14)
  {id:109,cat:"D",q:"During die prove-out, the first parts should be run at:",opts:["Maximum speed","Slow speed (inch mode/single stroke) to observe the die function safely","Normal production speed","Random speed"],ans:1,exp:"Always start at slow speed/single stroke to observe: strip feeding, pilot engagement, cutting, forming, and part ejection. Gradually increase speed once die function is verified.",type:"procedure"},
  {id:110,cat:"D",q:"Slug pulling (slugs sticking to the punch and being pulled back up) is corrected by:",opts:["Running faster","Adding positive slug retention (spring-loaded ejector in die, vacuum, or increased taper in die opening)","Ignoring it","Using bigger slugs"],ans:1,exp:"Slug pulling jams the die and causes double hits. Solutions: increase die clearance taper, add ejector pins, create vacuum relief, roughen the die bore, or add a slug kicker.",type:"critical"},
  {id:111,cat:"D",q:"Part dimensions are out of tolerance after heat treatment of the die. This is likely due to:",opts:["Machine error","Distortion from uneven heating/cooling or growth from retained austenite conversion","Blueprint error","Wrong material"],ans:1,exp:"Heat treatment causes: distortion (uneven heating/cooling), growth (austenite→martensite volume change), and possible decarburization. Allow grinding stock and stress-relieve between operations.",type:"critical"},
  {id:112,cat:"D",q:"Galling on a forming die surface is caused by:",opts:["Too much lubricant","Metal-to-metal adhesion from heat and pressure — workpiece material transfers to the die surface","Die too cold","Die too large"],ans:1,exp:"Galling: micro-welding of workpiece material to the die surface under pressure. Solutions: better lubrication, die coating (TiN, TiCN, TD), polish die surfaces, change die steel.",type:"critical"},
  {id:113,cat:"D",q:"A blanked part with a clean shear band on one side and a rough fracture zone on the other indicates:",opts:["Perfect clearance","Correct cutting action — shear zone from punch entry, fracture zone from material breakaway","Dull tools","Wrong material"],ans:1,exp:"Normal blanking produces: a small rollover at entry, clean shear band (~1/3 thickness), then rough fracture zone, and a burr. The relative proportions indicate clearance correctness.",type:"recall"},
  {id:114,cat:"D",q:"When proving a draw die, wrinkles in the drawn part indicate:",opts:["Correct blank holder pressure","Insufficient blank holder force — material is buckling instead of flowing smoothly","Too much lubricant","Correct die clearance"],ans:1,exp:"Wrinkling = material compressing rather than flowing into the die. Increase blank holder force, improve lubrication, adjust draw beads, or modify blank shape to control metal flow.",type:"critical"},
  {id:115,cat:"D",q:"Die timing is adjusted by:",opts:["Changing the press","Adding or removing shims under die components to change their engagement height relative to each other","Changing the material","Running faster"],ans:1,exp:"Shims under punches, form stations, or pad assemblies change when they engage the material during the stroke. This controls the sequence of operations and prevents interference.",type:"procedure"},
  {id:116,cat:"D",q:"Strip layout efficiency is calculated as:",opts:["Number of parts per strip","(Part area ÷ Strip area per pitch) × 100 = percentage of material used","Strip length × width","Parts per hour"],ans:1,exp:"Layout efficiency = usable part area vs total strip consumed. Higher efficiency = less scrap. Nesting, common-line cutting, and optimized strip width maximize material usage.",type:"recall"},
  {id:117,cat:"D",q:"A cracked punch during prove-out is likely caused by:",opts:["Correct hardness","Excessive hardness (under-tempered), insufficient clearance, misalignment, or shock loading","Too much clearance","Correct tempering"],ans:1,exp:"Punch cracking: too hard/brittle (under-tempered), too little clearance (excess force), misalignment (side loading), or punch too slender (buckling). Review heat treatment and die alignment.",type:"critical"},
  {id:118,cat:"D",q:"The press tonnage monitor shows the force approaching the press capacity. What action is needed?",opts:["Keep running","Stop immediately — investigate. Possible causes: dull tools, insufficient clearance, wrong material, or missing shear","Speed up","Ignore the alarm"],ans:1,exp:"Approaching press capacity risks die damage, press damage, and safety hazards. Stop, check: cutting clearances, tool sharpness, material type/thickness, shear on punches, and lubrication.",type:"procedure"},
  {id:119,cat:"D",q:"Scrap strip analysis during prove-out reveals:",opts:["Nothing useful","Strip feed accuracy, pilot engagement, mis-feeds, progression spacing, and overall die function","Only material waste","Only strip width"],ans:1,exp:"Examining the scrap strip is one of the most valuable diagnostic tools. It shows: pilot hole deformation (feed issues), station-to-station spacing, partial cuts, and die alignment.",type:"procedure"},
  {id:120,cat:"D",q:"A part sticking in the die cavity after forming is resolved by:",opts:["Hitting it with a hammer","Adding positive ejection (mechanical ejectors, spring pins, air blast) or improving surface finish/lubrication","Running the press faster","Ignoring it"],ans:1,exp:"Sticking: add mechanical ejectors or pneumatic blowoff, improve die surface finish (polish), apply proper lubrication, or increase draft angle on formed features.",type:"procedure"},
  {id:121,cat:"D",q:"After prove-out, the die clearances are documented because:",opts:["It's busywork","They establish the baseline for future sharpening and maintenance — knowing original clearances enables accurate restoration","Only for the inspector","To calculate cost"],ans:1,exp:"Baseline clearance records allow maintenance personnel to restore die clearances to original specs after sharpening. Without records, clearances drift and part quality degrades.",type:"recall"},
  {id:122,cat:"D",q:"Feed length accuracy in a progressive die is verified using:",opts:["A ruler","Measuring the pitch (station-to-station distance) on the strip with calipers or an optical comparator","Counting strokes","Weighing the strip"],ans:1,exp:"Measure pitch distance on the scrap strip between pilot holes. Must match the designed pitch within tolerance. Feed length errors accumulate, causing mis-registration at later stations.",type:"procedure"},

  // D-19: Repairs and Maintains Production Tools (13)
  {id:123,cat:"D",q:"When sharpening a blanking die, how much material is removed?",opts:["As much as possible","Only enough to restore a sharp cutting edge — typically 0.005-0.015\" per sharpening","1/4\" minimum","1\" to ensure sharpness"],ans:1,exp:"Remove only what's needed to restore the edge. Excessive grinding wastes die life (total regrind allowance is designed in). Track total material removed to know remaining die life.",type:"procedure"},
  {id:124,cat:"D",q:"After sharpening a die, what must be adjusted?",opts:["Nothing","Shut height — add shims equal to the material removed to maintain correct press stroke position","Only the lubrication","Only the feed length"],ans:1,exp:"Grinding reduces die height. Add shims under the sharpened section equal to the amount removed to maintain original shut height and ensure proper strip-to-die clearance.",type:"procedure"},
  {id:125,cat:"D",q:"A die producing parts with increasing burr over time indicates:",opts:["Correct operation","Cutting edges are wearing/dulling and need sharpening","Material is getting softer","Press is slowing down"],ans:1,exp:"Burr height increases as cutting edges wear. When burr exceeds acceptable limits (typically 0.003-0.005\"), the die must be removed and cutting edges resharpened.",type:"recall"},
  {id:126,cat:"D",q:"Chipping on a punch cutting edge is typically caused by:",opts:["Normal wear","Excessive hardness (under-tempered), improper clearance, misalignment, or shock from mis-feed","Correct clearance","Good lubrication"],ans:1,exp:"Edge chipping: too hard/brittle (increase tempering), too little clearance (increase), misalignment (realign), mis-feeds impacting the punch (check feed system). Repair by resharpening below the chipped area.",type:"critical"},
  {id:127,cat:"D",q:"A broken die spring is replaced with one of:",opts:["Any available spring","The same colour code (force rating), length, and bore/OD dimensions as the original","A bolt instead","A rubber band"],ans:1,exp:"Springs must match: force rating (colour code), free length, solid height, bore diameter, and OD. Wrong spring force causes poor stripping, part quality issues, or die damage.",type:"procedure"},
  {id:128,cat:"D",q:"When a die guide bushing is worn beyond tolerance, it should be:",opts:["Left alone","Replaced with a new bushing of the same size, or rebored oversize and fitted with an oversize pin","Lubricated more","Shimmed"],ans:1,exp:"Worn guide bushings cause upper/lower misalignment. Replace with same-size bushing, or if the bore is damaged, ream oversize and fit a matching oversize guide pin.",type:"procedure"},
  {id:129,cat:"D",q:"Preventive maintenance on a production die should include:",opts:["Nothing between failures","Regular inspection of cutting edges, clearances, springs, guide components, and lubrication at scheduled intervals","Only cleaning","Only painting"],ans:1,exp:"PM schedule: inspect cutting edges (burr check), verify clearances, check spring condition, lubricate guide components, inspect pilots, check fastener torque, and document findings.",type:"recall"},
  {id:130,cat:"D",q:"A cracked die section can sometimes be repaired by:",opts:["Taping it","Welding with appropriate filler and procedure, then re-machining, re-hardening, and re-grinding","Gluing","Ignoring the crack"],ans:1,exp:"Some tool steels can be repair-welded by experienced tool steel welders: preheat, weld with matching filler, slow cool, re-heat-treat, then re-machine/grind. Not all cracks are repairable.",type:"procedure"},
  {id:131,cat:"D",q:"TiN (Titanium Nitride) coating on die components provides:",opts:["Only gold colour","Increased surface hardness, reduced friction, improved wear resistance, and anti-galling properties","Only corrosion protection","Only aesthetics"],ans:1,exp:"TiN and similar PVD coatings (TiCN, TiAlN, CrN) dramatically extend die life by reducing adhesive wear, lowering friction, and preventing galling. Applied after final grinding.",type:"recall"},
  {id:132,cat:"D",q:"Tracking die maintenance history helps determine:",opts:["Nothing useful","Die life expectancy, sharpening intervals, recurring problems, and when to rebuild or replace","Only part count","Only material cost"],ans:1,exp:"Maintenance history reveals: average strokes between sharpenings, common failure modes, total regrind consumed, parts produced, and helps predict when a die needs major rebuild or replacement.",type:"recall"},
  {id:133,cat:"D",q:"A forming die producing parts with inconsistent dimensions should be checked for:",opts:["Paint condition","Worn or broken springs, worn guides, loose fasteners, or material variation","Only press speed","Only temperature"],ans:1,exp:"Inconsistency: worn springs (uneven pressure), worn guides (shifting alignment), loose bolts (components moving), material variation (different lots), or press ram issues.",type:"procedure"},
  {id:134,cat:"D",q:"When a die is stored for extended periods, what preservation is needed?",opts:["Nothing","Clean, apply rust preventive, close the die, and store in a dry area with documentation","Just stack it in a corner","Leave it in the press"],ans:1,exp:"Long-term storage: clean thoroughly, apply rust preventive oil/coating on all precision surfaces, close the die, tag with identification and maintenance status, store in climate-controlled area.",type:"procedure"},
  {id:135,cat:"D",q:"The total die life is determined by:",opts:["Only the initial build quality","Initial quality + total regrind allowance + maintenance quality. Tracked as total strokes before major rebuild.","Only the press speed","Only the material"],ans:1,exp:"Die life = function of: design quality, steel selection, heat treatment, clearances, lubrication, maintenance discipline, and total regrind stock available. Good PM extends die life significantly.",type:"recall"},
];
